name: CI
on: 
  workflow_dispatch:
    inputs:
      url:
        required: true
        description: url

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    
      - uses: actions/checkout@v3
      
      - name: Set up Python 3.10
        uses: actions/setup-python@v2
        with:
          python-version: "3.10"

      - name: Run a one-line script
        run: pip install -r requirements.txt

      - name: Run a multi-line script
        timeout-minutes: 3
        env:
          URL: ${{github.event.inputs.url}}
        run: python scripts/islive.py
